// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ckfqewhkqngxjhwqjfln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrZnFld2hrcW5neGpod3FqZmxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MDY3MjksImV4cCI6MjA3NDA4MjcyOX0.TGId-8ashgaKkEPaFtkuBbZ1BPqGCK6pzPnqa1-5rPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});